import type { Metadata } from 'next'
import '../globals.css'
import WebHeader from '@/components/header'
import WebFooter from '@/components/footer'

export const metadata: Metadata = {
  title: 'Edutrail Blaze',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <WebHeader />
        {children}
        <WebFooter />
      </body>
    </html>
  )
}
