import type { Metadata } from 'next'
import '../globals.css'
import WebHeader from '@/components/global/header/header'
import WebFooter from '@/components/global/footer/footer'

export const metadata: Metadata = {
  title: 'Edutrail Blaze',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <WebHeader />
      <div className='min-h-screen'>{children}</div>
      <WebFooter />
    </>
  )
}
