import type { Metadata } from 'next'
import InstructorSidebar from '@/components/user/instructor/sidebar/InstructorSidebar'

export const metadata: Metadata = {
  title: 'Edutrail Blaze',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <InstructorSidebar />
      <div className='ml-16 min-h-screen'>{children}</div>
    </>
  )
}
