import type { Metadata } from 'next'
import './globals.css'
import SessionProviderWrapper from '../providers/SessionProviderWrapper'
import { StoreProvider } from '../providers/StoreProvider'

export const metadata: Metadata = {
  title: 'EduTrailBlaze',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <SessionProviderWrapper>
          <StoreProvider>{children}</StoreProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  )
}
