import type { Metadata } from 'next'
import './globals.css'
import SessionProviderWrapper from '../providers/SessionProviderWrapper'
import { StoreProvider } from '../providers/StoreProvider'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

export const metadata: Metadata = {
  title: 'EduTrailBlaze',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <SessionProviderWrapper>
          <StoreProvider>
            <ToastContainer
              position='top-right'
              autoClose={5000}
              hideProgressBar={false}
              closeOnClick={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme='light'
            />
            {children}
          </StoreProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  )
}
