import type { Metadata } from 'next'
import InstructorHeader from '@/components/user/instructor/instructorHeader/InstructorHeader'
import WebFooter from '@/components/global/footer/footer'
import '@/app/(user)/instructor/layout.css'
import InstructorEditSidebar from '@/components/user/instructor/sidebar/InstructorEditSidebar'

export const metadata: Metadata = {
  title: 'Edutrail Blaze',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <div className='sticky top-0 z-10'>
        <InstructorHeader />
      </div>
      <InstructorEditSidebar />
      <div className='ml-16 min-h-screen'>{children}</div>
      <WebFooter />
    </>
  )
}


