import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'
import { BASE_URL } from '@/utils/config'

export const dashboardApi = createApi({
  reducerPath: 'dashboard/api',
  baseQuery: fetchBaseQuery({ baseUrl: BASE_URL }),
  endpoints: (builder) => ({
    // GET /api/AdminDashboard/number-of-instructors
    getNumberOfInstructors: builder.query<number, void>({
      query: () => 'AdminDashboard/number-of-instructors'
    }),

    // GET /api/AdminDashboard/number-of-students
    getNumberOfStudents: builder.query<number, void>({
      query: () => 'AdminDashboard/number-of-students'
    }),

    // GET /api/AdminDashboard/total-revenue
    getTotalRevenue: builder.query<number, void>({
      query: () => 'AdminDashboard/total-revenue'
    }),

    // GET /api/AdminDashboard/total-courses-bought
    getTotalCoursesBought: builder.query<number, void>({
      query: () => 'AdminDashboard/total-courses-bought'
    })
  })
})

// Export hooks generated by RTK Query
export const {
  useGetNumberOfInstructorsQuery,
  useGetNumberOfStudentsQuery,
  useGetTotalRevenueQuery,
  useGetTotalCoursesBoughtQuery
} = dashboardApi
